/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUNaWnJRRzdQcEZxM0VMd0VRUXBBeWNJRnJPZ1VlVHJmYVFtdzdOUmZIST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUFNJWVBrRU96Ynl3ejRzeXNuYlQrNE4xazJmVU5FZGhIUEdxS0psbnNDST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4REdxZGtXeUJXaEcvN1lIQWJrSnVabm1Rckp0dk9ZZVZLOElyY25qREVZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJmL3BpYWVheTdQbm5aa0hFb243eDU3K0xyTFpSYkZiYmZHUHd0TUQxOEg0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVITVdSWEdERXl4OGp3T1JWSW9ZMVRhVm1xZkdrMmJKcEtXY2o4MVc0MGs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Iko2RzN6eW1ScGh6bzZ2UDRFWHN1ZFdsOTB2TloxL0N2bThBM2dEa1NtaGc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUx5RVFCZXUydmVtK3VneUpjOG1mUzJ1aU5TcWlJRU03SzlGbVVtc2hIcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0oxdEpERk9yckhqUW55dEpwa1dxYjBhcUZmTmk3S3B1QUhIcWowTDJHYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjF3cGRxUkNMbUZ0NmswRVdKckM4VXZvWWJVTHJpVnNETENidjM3WmJnclNaZ3Q2Z2kvWXQzQksxUHlTOVF0c2E1TUdhckRTSTk5VmhkSWtQaHJ6bWdRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODUsImFkdlNlY3JldEtleSI6IndQOEcrS0tJK0NlTis0aHFtbkV3S1FIeDlMaFEvWkVtaytzbXA1OEM0NGs9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0MTEyMTkyMTE5QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkQ5NjNGOEIzRkU4MkQ4MEM5ODEzM0Q5NzMxRkMwQkNBIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MjgyMzA3NTl9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDExMjE5MjExOUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI1N0Q0QTBDOTczNEM3RjA4NUE0MjYyOTAzRkI4NDZGMyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzI4MjMwNzU5fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQxMTIxOTIxMTlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQzBEODFGOEQ4RDg3RTAxOTg1MDc4RjkzM0VERTBFQkIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIzMDc5N31dLCJuZXh0UHJlS2V5SWQiOjMyLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzIsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiTmt3ek1ydVZSVUNRNUhaZGF0a0dKQSIsInBob25lSWQiOiIzNDE1MDllNy0zY2NjLTQwODgtYmUwMC0yYTkyYWI4N2I5OGQiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY25MNUg1K1ZuTGtzMVhjRG5ENTJuYloyUzFvPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkV5bzcwQXRnK0hpc3JLOXBlRkZzWHBwb2xoQT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiI5RVY4S1RLRSIsIm1lIjp7ImlkIjoiMjU0MTEyMTkyMTE5OjgyQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCdkILNhsy68J2QgM2GzLrwnZCSzYbMuvCdkITNhsy68J2QmM2GzLrwnZCRzYbMuvCdkIfNhsy68J2Qjs2GzLrwnZCDzYbMuvCdkITNhsy68J2Qks2GzLoifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xhUDFac0JFTS9xaXJnR0dBZ2dBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlJmTFh1ZG9OcWQ3d1RaRU9VczFoRm0wUVp0eHU0Wm1NNEZSbE00M3BQZ3M9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImhabmZpekg5ZTFZR1ZhdllscHdLa0o4aEd6WGEyZVZ2aTA5QzFHWSt4WGx4ck1JWDc5MlFndUR1Y01HL3BhM0VmaFd2a0xoV2NzN2tSazJzNS9la0F3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJ5c045RW5udW5qaW5LSDE4Ym1oRWowVVYwYXFvOWswZ01XWll5OG9tOUxrV2o1Nk80M2NDWWp3ZlVCR3NsK0hpS3dUNExQU1hRQU5OOWU2Q3dqR1Fodz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDExMjE5MjExOTo4MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJVWHkxN25hRGFuZThFMlJEbExOWVJadEVHYmNidUdaak9CVVpUT042VDRMIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI4MjMwNzQ4LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU56RSJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'CASEYRHODES🌟';
const packname = process.env.PACKNAME || 'CHARITY MD🤖';
const dev = process.env.DEV || '254112192119';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'CASRYRHODES🌟';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
