/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaU5HTjFyTmhraWJOcDFVbnV2S0NuWmZBY3NUSDdReFJtOGVWRHpTMkduTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNHVqUmVTOU80azRuQjV1aDZtOVRFaG5ib2xCM29SMVlGVnNZaWRJQUhFaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZQkJLUFhDcXd6RThNeTFlMnU1MUZOY1k0a2t6WXdSbm16cTJWRXl0NDBjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJWa2ozV3FVYzAyRVJqN2FoSUxYTGxIdjdRbTBJWXdhMTNKbENzUUtaSWwwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZKWWhZRTcvcGNiM3pIRUY4NC9EbUF2QXBqOUtCRy9hUllUbmdNZEszR2s9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9yd1llbStRKzJRWnhyY2wwYThFZlZWa2xRSUFzeFp4V1k2WFd0UkY4UWs9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEpDSlM5ZWw5MEhRZDJwYXdGVFRnN1d1MGhjKzhXSzhYRFAzbDlteFFIUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWVlTY21OU3dLcy84eFJxZm9zZkRhdG1STWp1VVVqM0orS2ZJUkxZNlhrTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNyeU1XVk5HdG1SWDJUMGxSWDRyOTZCRVVJbWhVZ1N3ODZzdVUzZEZXRXZzL1Z3SUcvR0tjRHdoeEVib3FVQ09wUjBucmJYN2laUWFlUW01R1c5V0RnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NywiYWR2U2VjcmV0S2V5IjoiU0NlYjNxQnI3WmFOb2oxOHJPcytiMFF4NkhrU0pKQWFPZVlxUnRTL0Q1UT0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiM3FfU1lxVTZSMHUzV2hUMDdLRWx6USIsInBob25lSWQiOiJiZGYwZDU2ZS04MjVkLTQ5YmQtYjcxOC03MDQ2MDZlZDY4ZjYiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTmc2TUtaUWxJbnFTd0x6dXdwcUJNR2YvR0dJPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImM2VEN4MFJEd3dxQXhwbU5iS1JpQkg3cURuRT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiI4RjdUS1lMVyIsIm1lIjp7ImlkIjoiMjU0MTEyMTkyMTE5OjcyQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCdkILNhsy68J2QgM2GzLrwnZCSzYbMuvCdkITNhsy68J2QmM2GzLrwnZCRzYbMuvCdkIfNhsy68J2Qjs2GzLrwnZCDzYbMuvCdkITNhsy68J2Qks2GzLoifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xXUDFac0JFSVMxZ2JnR0dBb2dBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlJmTFh1ZG9OcWQ3d1RaRU9VczFoRm0wUVp0eHU0Wm1NNEZSbE00M3BQZ3M9IiwiYWNjb3VudFNpZ25hdHVyZSI6InRsc0pIYnE1NGxHM3JPczZDenRBbTFnMFpwVlJLRUJGdlovK0tTNnlucDFxL3gxbVBOamN4UjkyU29BQ09HN2RVazh2ajh6alBWb0ppUnIxYVdlb0RRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJVSnhieGZYc1d4ci9RV3dHakxpWkJVK0UzUDdmMGhjeWNxMll2SkU4bTNZZ0owU3FISEJCeXpEM0k2Lzk1Y0lESVd0VmVjOE8yRVJMRFA1MDRFdTVBdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDExMjE5MjExOTo3MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJVWHkxN25hRGFuZThFMlJEbExOWVJadEVHYmNidUdaak9CVVpUT042VDRMIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI4MDc2NDMzfQ=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'CASEYRHODES🌟';
const packname = process.env.PACKNAME || 'CHARITY MD🤖';
const dev = process.env.DEV || '254112192119';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'CASRYRHODES🌟';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
